name: BlissfulCoreSpigot
version: '1.0-SNAPSHOT'
main: tortel.blissfulcorespigot.Main
api-version: '1.20'

commands:
  emojis:
    aliases:
      - e
  toggleteamnames:
    description: toggles team names from community to official and vice versa
